# Generated by go2rpm 1
%bcond_without check

# https://github.com/coyim/gotk3adapter
%global goipath         github.com/coyim/gotk3adapter
%global commit          8ad62a930093c5c48a13619223885d6ac3418bb0

%gometa

%global common_description %{expand:
Contains adapters and interfaces for gotk3 in order to make testing possible.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Contains adapters and interfaces for gotk3 in order to make testing possible

License:        GPL-3.0-only
# FIXME: Upstream uses unknown SPDX tag GPL-3.0-only!
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gotk3/gotk3/gdk)
BuildRequires:  golang(github.com/gotk3/gotk3/glib)
BuildRequires:  golang(github.com/gotk3/gotk3/gtk)
BuildRequires:  golang(github.com/gotk3/gotk3/pango)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Mar 16 12:21:32 -05 2020 rafael <rafael@autonomia.digital> - 0-0.1.20200316git8ad62a9
- Initial package

