# Generated by go2rpm 1
%bcond_without check

# https://github.com/coyim/gotk3adapter
%global goipath         github.com/coyim/gotk3adapter
Version:                0.0.2

%gometa

%global common_description %{expand:
Contains adapters and interfaces for gotk3 in order to make testing possible.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        0.1%{?dist}
Summary:        Contains adapters and interfaces for gotk3 in order to make testing possible

License:        GPL-3.0-only
# FIXME: Upstream uses unknown SPDX tag GPL-3.0-only!
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gotk3/gotk3/gdk)
BuildRequires:  golang(github.com/gotk3/gotk3/glib)
BuildRequires:  golang(github.com/gotk3/gotk3/gtk)
BuildRequires:  golang(github.com/gotk3/gotk3/pango)
BuildRequires:  golang(github.com/coyim/gotk3extra)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall


%if %{with check}
%check
Xvfb :99 &
export DISPLAY=:99
export GOFLAGS="-tags=gtk_3_18,glib_2_66"
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Apr 30 11:00:00 -05 2023 CAD <fedora@autonomia.digital> - 0.0.2-1
- Update to released version.
* Mon Apr 13 11:14:32 -05 2020 rafael <rafael@autonomia.digital> - 0-0.2.20200413git596a627
- Update to git version 728d69a7102fc174d4d7ef16eaf527e2601f0c69
* Mon Mar 16 12:21:32 -05 2020 rafael <rafael@autonomia.digital> - 0-0.1.20200316git8ad62a9
- Initial package
